events {}

http {
    upstream backend {
        server app1:8080;
        server app2:8080;
        server app3:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://backend;

            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";

            proxy_set_header Host $host;

            proxy_read_timeout 600s;
            proxy_send_timeout 600s;

            proxy_cache_bypass $http_upgrade;
        }
    }
}